mode: all
min_length: 3
ignore_files:
  - '*test.go'
allowed:
  - aspell
  - repo
  - failsafe
  - golang
  - mkdir
  - apk
  - ubuntu
  - golangci
  - splitted
  - mri
  - IID
  - repo
  - OPTIM
  - Submatch
  - Lshortfile
  - MAXSUBJECTLEN
  - MAXSUBJECTPARTS
  - MINSUBJECTLEN
  - MINSUBJECTPARTS
  - malformatted
  - cmdline
  - sed
  - runnumber
  - LLC
  - devel
