mode: all
min_length: 3
ignore:
  - '*_test.go'
allowed:
  - aspell
  - repo
  - yaml
  - config
  - Github
  - Gitlab
  - env
  - failsafe
  - golang
  - mkdir
  - WORKDIR
  - apk
  - ENTRYPOINT
  - ubuntu
  - golangci
  - splitted
  - sudo
  - mri
  - IID
  - repo
  - OPTIM
  - Submatch
  - Lshortfile
  - MAXSUBJECTLEN
  - MAXSUBJECTPARTS
  - MINSUBJECTLEN
  - MINSUBJECTPARTS
  - malformatted
  - cmdline
  - Dockerfile
  - ghcr
  - sed
  - stdin
  - runnumber
